{% set name = "libnetworkit" %}
{% set version = "9.1.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "0376b3b7b8ba1fefb46549c7dd2cf979237a24708293715b1da92b4da272a742" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - url: 'https://github.com/networkit/networkit/archive/{{ version }}.tar.gz'
    {{ hash_type }}: {{ hash_value }}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake  >=3.6
    - make
    - llvm-openmp  # [osx]
    - libtlx
  host:
    - _openmp_mutex  # [linux]

test:
  requires:
    - conda-build
  commands:
    # Verify headers are present
    - test -f $PREFIX/include/networkit/Globals.hpp  # [unix]
    - test -f %LIBRARY_PREFIX%\include\networkit\Globals.hpp  # [win]

    # Verify pkg-config file is present
    - test -f $PREFIX/lib/pkgconfig/networkit.pc  # [unix]
    - test -f %LIBRARY_PREFIX%\lib\pkgconfig\networkit.pc  # [win]

    # Verify shared library is present
    - test -f $PREFIX/lib/libnetworkit.so  # [linux]
    - test -f $PREFIX/lib/libnetworkit.dylib  # [osx]
    - test -f %LIBRARY_PREFIX%\lib\networkit.lib  # [win]
    - test -f %LIBRARY_PREFIX%\lib\networkit\networkit_state.dll  # [win]

    # conda tools
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/networkit/networkit
  license: MIT
  license_family: MIT
  license_file: License.txt
  summary: 'NetworKit is a growing open-source toolkit for large-scale network analysis.'
  description: |
           NetworKit is a growing open-source toolkit for large-scale network analysis. Its aim is to provide tools for the analysis of large networks in the size range from thousands to billions of edges. For this purpose, it implements efficient graph algorithms, many of them parallel to utilize multicore architectures. These are meant to compute standard measures of network analysis, such as degree sequences, clustering coefficients, and centrality measures. In this respect, NetworKit is comparable to packages such as NetworkX, albeit with a focus on parallelism and scalability. NetworKit is also a testbed for algorithm engineering and contains novel algorithms from recently published research (see list of Publications).
  doc_url: https://networkit.github.io/
  dev_url: https://github.com/networkit/networkit

extra:
  recipe-maintainers:
    - angriman
    - avdgrinten
    - fabratu
